dependencies:
  cli:
    path: ../../../../pkg-cli
  fs:
    url: github.com/toitlang/pkg-fs
    version: ^2.3.1
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.15.1
  tar:
    url: github.com/toitlang/pkg-tar
    version: ^1.2.0
