dependencies:
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.3.0
  fs:
    url: github.com/toitlang/pkg-fs
    version: ^1.0.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.11.0
  tar:
    url: github.com/toitlang/pkg-tar
    version: ^1.0.0
