dependencies:
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^2.1.0
  fs:
    url: github.com/toitlang/pkg-fs
    version: ^2.3.1
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.15.3
  tar:
    url: github.com/toitlang/pkg-tar
    version: ^1.2.0
