dependencies:
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.1.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.4.1
  tar:
    url: github.com/toitlang/pkg-tar
    version: ^1.0.0
