// Code generated by tedi; DO NOT EDIT.

package cmd

import (
	"github.com/jstroem/tedi"
	"os"
	"testing"
)

func TestMain(m *testing.M) {
	t := tedi.New(m)

	// TestLabels:
	t.TestLabel("unit")
	t.TestLabel("integration")
	t.TestLabel("regression")

	// Fixtures:
	t.Fixture(fixToitcPath)
	t.Fixture(fixToitlspPath)
	t.Fixture(fixCWDPath)

	// Tests:
	t.Test("testAnalyze", testAnalyze, "unit")
	t.Test("testArchive", testArchive, "unit")

	os.Exit(t.Run())
}
