// Copyright (C) 2026 Toit contributors.
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; version
// 2.1 only.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// The license can be found in the file `LICENSE` in the top level
// directory of this repository.

import crypto.sha256 as crypto
import io show LITTLE-ENDIAN
import .rp2350 as firmware-rp2350

UF2-BLOCK-SIZE_ ::= 512
UF2-PAYLOAD-SIZE_ ::= 256
UF2-MAGIC-START-0_ ::= 0x0a32_4655
UF2-MAGIC-START-1_ ::= 0x9e5d_5157
UF2-MAGIC-END_ ::= 0x0ab1_6f30
UF2-FLAG-FAMILY_ ::= 0x0000_2000
UF2-FLAG-EXTENSIONS_ ::= 0x0000_8000
UF2-FAMILY-ABSOLUTE_ ::= 0xe48b_ff57
UF2-IGNORE-BLOCK_ ::= 0x9957_e304

XIP-BASE_ ::= 0x1000_0000
SLOT-A-OFFSET_ ::= 0x0000_2000
SLOT-SIZE_ ::= 4 * 1024 * 1024
ABSOLUTE-BLOCK-ADDRESS_ ::= 0x10ff_ff00

// This is the partition-table item generated by picotool 2.3.1 from
// toolchains/rp2350/partitions-experimental.json. Keeping it structural here
// prevents an envelope from silently provisioning a different physical layout.
PARTITION-TABLE-WORDS_ ::= [
  0x0300_160a,  // Three non-singleton partitions; 22 words.
  0xcc00_8000,  // Unpartitioned: S/NSBOOT rw, absolute UF2 family.
  0xcc80_2002, 0xcc02_1001, 0, 0, 0x696f_5406, 0x0041_2074,
  0xcd00_2402, 0xcc02_1003, 1, 0, 0x696f_5406, 0x0042_2074,
  0xcdff_8802, 0xcc01_3001, 2, 0,
  0x696f_540d, 0x6572_2074, 0x7473_6967, 0x0000_7972,
]

invalid-partition-table_ -> none:
  throw "Invalid RP2350 bootstrap partition-table UF2"

word_ bytes/ByteArray offset/int -> int:
  if offset < 0 or offset + 4 > bytes.size or offset & 3 != 0:
    invalid-partition-table_
  return LITTLE-ENDIAN.uint32 bytes offset

put_ bytes/ByteArray offset/int value/int -> none:
  LITTLE-ENDIAN.put-uint32 bytes offset (value & 0xffff_ffff)

partition-payload_ uf2/ByteArray -> ByteArray:
  if uf2.size != UF2-BLOCK-SIZE_: invalid-partition-table_
  if (word_ uf2 0) != UF2-MAGIC-START-0_ or
      (word_ uf2 4) != UF2-MAGIC-START-1_ or
      (word_ uf2 8) != UF2-FLAG-FAMILY_ or
      (word_ uf2 12) != XIP-BASE_ or
      (word_ uf2 16) != UF2-PAYLOAD-SIZE_ or
      (word_ uf2 20) != 0 or
      (word_ uf2 24) != 1 or
      (word_ uf2 28) != UF2-FAMILY-ABSOLUTE_ or
      (word_ uf2 (UF2-BLOCK-SIZE_ - 4)) != UF2-MAGIC-END_:
    invalid-partition-table_

  payload := uf2[32..32 + UF2-PAYLOAD-SIZE_]
  if (word_ payload 0) != 0xffff_ded3: invalid-partition-table_
  PARTITION-TABLE-WORDS_.size.repeat: | index/int |
    expected/int := PARTITION-TABLE-WORDS_[index]
    if (word_ payload (4 + index * 4)) != expected: invalid-partition-table_

  if (word_ payload 0x5c) != 0x248 or (word_ payload 0x60) != 0x0001_0000:
    invalid-partition-table_
  if (word_ payload 0x64) != 0x0100_0247 or (word_ payload 0x68) != 27:
    invalid-partition-table_
  if (word_ payload 0x6c) != 0x94b: invalid-partition-table_
  if (crypto.sha256 payload[..0x6c]) != payload[0x70..0x90]:
    invalid-partition-table_
  if (word_ payload 0x90) != 0x23ff or
      (word_ payload 0x94) != 0 or
      (word_ payload 0x98) != 0xab12_3579:
    invalid-partition-table_
  for offset := 0x9c; offset < payload.size; offset++:
    if payload[offset] != 0: invalid-partition-table_
  return payload

/** Validates the exact partition-table UF2 required by Toit's RP2350 layout. */
validate-partition-table uf2/ByteArray -> none:
  partition-payload_ uf2

write-block_ output/ByteArray at/int
    --flags/int
    --target/int
    --block-number/int
    --block-count/int
    --family/int
    payload/ByteArray -> none:
  if payload.size != UF2-PAYLOAD-SIZE_: throw "Invalid UF2 payload size"
  put_ output at UF2-MAGIC-START-0_
  put_ output (at + 4) UF2-MAGIC-START-1_
  put_ output (at + 8) flags
  put_ output (at + 12) target
  put_ output (at + 16) UF2-PAYLOAD-SIZE_
  put_ output (at + 20) block-number
  put_ output (at + 24) block-count
  put_ output (at + 28) family
  output.replace (at + 32) payload
  put_ output (at + UF2-BLOCK-SIZE_ - 4) UF2-MAGIC-END_

/**
Builds a blank-board recovery UF2 containing the partition table and slot A.

The UF2 writes only the partition-table page and the populated prefix of the
  physical slot-A partition. It never addresses slot B or the registry.
*/
build-image firmware/ByteArray --partition-table/ByteArray -> ByteArray:
  if firmware.is-empty or firmware.size > SLOT-SIZE_:
    throw "RP2350 bootstrap firmware exceeds the slot-A partition"
  // A recovery load has no slot-A FLASH_UPDATE reboot. Mirror the ROM's
  // explicit-buy result so this image is eligible for an ordinary boot.
  confirmed := firmware-rp2350.confirmed-recovery-image firmware
  partition-payload := partition-payload_ partition-table
  firmware-blocks := (confirmed.size + UF2-PAYLOAD-SIZE_ - 1) / UF2-PAYLOAD-SIZE_
  main-blocks := 1 + firmware-blocks
  result := ByteArray ((1 + main-blocks) * UF2-BLOCK-SIZE_)

  // RP2350-E10 workaround. The extension marks this absolute block as ignored;
  // it is deliberately outside the partitions and does not count as a main
  // UF2 data block.
  ignored := ByteArray UF2-PAYLOAD-SIZE_
  UF2-PAYLOAD-SIZE_.repeat: ignored[it] = 0xef
  write-block_ result 0
      --flags=(UF2-FLAG-FAMILY_ | UF2-FLAG-EXTENSIONS_)
      --target=ABSOLUTE-BLOCK-ADDRESS_
      --block-number=0
      --block-count=2
      --family=UF2-FAMILY-ABSOLUTE_
      ignored
  put_ result (32 + UF2-PAYLOAD-SIZE_) UF2-IGNORE-BLOCK_

  write-block_ result UF2-BLOCK-SIZE_
      --flags=UF2-FLAG-FAMILY_
      --target=XIP-BASE_
      --block-number=0
      --block-count=main-blocks
      --family=UF2-FAMILY-ABSOLUTE_
      partition-payload

  firmware-blocks.repeat: | index/int |
    from := index * UF2-PAYLOAD-SIZE_
    to := min confirmed.size (from + UF2-PAYLOAD-SIZE_)
    payload := ByteArray UF2-PAYLOAD-SIZE_
    payload.replace 0 confirmed[from..to]
    write-block_ result ((index + 2) * UF2-BLOCK-SIZE_)
        --flags=UF2-FLAG-FAMILY_
        --target=(XIP-BASE_ + SLOT-A-OFFSET_ + from)
        --block-number=(index + 1)
        --block-count=main-blocks
        --family=UF2-FAMILY-ABSOLUTE_
        payload
  return result
