// Copyright (C) 2026 Toit contributors.
// Use of this source code is governed by a Zero-Clause BSD license that can
// be found in the tests/LICENSE file.

import expect show *
import encoding.hex
import system
import ble.experimental.bond as bonds
import ble.experimental.bond-flash
import ble.experimental.cccd-storage
import ble.experimental.smp-identity show Identity
import .ble-bond-table-test as fixture

DATABASE-ID ::= #[3, 2, 1]
STATE ::= #[1, 1, 4, 0, 1, 0]

candidate -> bonds.Candidate:
  local := Identity (ByteArray 16) #[1, 2, 3, 4, 5, 6] 0
  peer := Identity (ByteArray 16 --initial=2) #[6, 5, 4, 3, 2, 1] 0
  return bonds.Candidate (ByteArray 16 --initial=1) local peer --authenticated

main:
  protected-records
  faults
  flash-reopen

class Records extends fixture.MemoryRecords:
  ignore-write/bool := false
  mutate/bool := false
  constructor entries/Map: super entries
  write name/string bytes/ByteArray -> none:
    if ignore-write: return
    if mutate: bytes[20] ^= 1
    super name bytes

class OtherNamespace extends Records:
  constructor entries/Map: super entries
  namespace -> ByteArray: return #[7, 8, 10]

protected-records:
  key := ByteArray 32 --initial=42
  records := Records {:}
  bank := cccd-storage.Storage records key
  key.fill 0
  bond := candidate
  revision := DATABASE-ID.copy
  store := bank.session 0 bond --database-id=revision
  revision.fill 0
  expect-null store.load
  // Independently generated by cryptography AESGCM with the public fixture key.
  known := hex.decode "54434301000102030405060708090a0b4d2c50489d23a59036931cb78145de194f11df762547"
  records.entries["cccd/0"] = known.copy
  expect-equals STATE store.load
  bytes := STATE.copy
  store.save bytes
  bytes.fill 0
  original := (records.entries["cccd/0"] as ByteArray).copy
  store.save STATE
  expect (original != records.entries["cccd/0"])
  retained := store.load
  retained.fill 0
  system.process-stats --gc
  expect-equals STATE store.load
  original.size.repeat: | index/int |
    altered := original.copy
    altered[index] ^= 1
    records.entries["cccd/0"] = altered
    expect-throw "BLE_INVALID_SEALED_CCCD": store.load
  [#[], original[..original.size - 1], original + #[0], ByteArray 291].do: | invalid/ByteArray |
    records.entries["cccd/0"] = invalid
    expect-throw "BLE_INVALID_SEALED_CCCD": store.load
  records.entries["cccd/0"] = original
  other-key := cccd-storage.Storage (Records records.entries) (ByteArray 32 --initial=41)
  try:
    expect-throw "BLE_INVALID_SEALED_CCCD":
      (other-key.session 0 bond --database-id=DATABASE-ID).load
  finally:
    other-key.close
  expect-throw "BLE_INVALID_SEALED_CCCD":
    (bank.session 0 bond --database-id=#[3, 2, 2]).load
  expect-throw "BLE_INVALID_SEALED_CCCD":
    (bank.session 0 bond --database-id=#[3, 2, 2]).save STATE
  expect-equals original records.entries["cccd/0"]
  other-namespace := cccd-storage.Storage (OtherNamespace records.entries) (ByteArray 32 --initial=42)
  try:
    expect-throw "BLE_INVALID_SEALED_CCCD":
      (other-namespace.session 0 bond --database-id=DATABASE-ID).load
  finally:
    other-namespace.close
  changed := bonds.Candidate (ByteArray 16 --initial=2) bond.local bond.peer --authenticated
  expect-throw "BLE_INVALID_SEALED_CCCD":
    (bank.session 0 changed --database-id=DATABASE-ID).load
  changed = bonds.Candidate bond.key bond.local bond.peer --no-authenticated
  expect-throw "BLE_INVALID_SEALED_CCCD":
    (bank.session 0 changed --database-id=DATABASE-ID).load
  changed-peer := Identity bond.peer.irk #[8, 7, 6, 5, 4, 3] 0
  changed-local := Identity bond.local.irk #[3, 4, 5, 6, 7, 8] 0
  changed-irk := Identity (ByteArray 16 --initial=3) bond.peer.address 0
  [
    bonds.Candidate bond.key bond.local changed-peer --authenticated,
    bonds.Candidate bond.key changed-local bond.peer --authenticated,
    bonds.Candidate bond.key bond.local changed-irk --authenticated,
  ].do: | context/bonds.Candidate |
    expect-throw "BLE_INVALID_SEALED_CCCD":
      (bank.session 0 context --database-id=DATABASE-ID).load
  records.entries["cccd/1"] = original.copy
  expect-throw "BLE_INVALID_SEALED_CCCD":
    (bank.session 1 bond --database-id=DATABASE-ID).load
  expect-equals STATE store.load
  [#[], ByteArray 65].do: | invalid/ByteArray |
    expect-throw "INVALID_ARGUMENT": bank.session 0 bond --database-id=invalid
  [-1, 255].do: | invalid/int |
    expect-throw "INVALID_ARGUMENT": bank.session invalid bond --database-id=DATABASE-ID
  [#[], ByteArray 1024].do: | invalid/ByteArray |
    expect-throw "INVALID_ARGUMENT": store.save invalid
  bank.close
  bank.close
  expect-equals 1 records.closes
  expect-throw "BLE_CCCD_STORAGE_CLOSED": store.load
  expect-throw "BLE_CCCD_STORAGE_CLOSED": store.save STATE

faults:
  records := Records {:}
  bank := cccd-storage.Storage records (ByteArray 32 --initial=42)
  first := bank.session 0 candidate --database-id=DATABASE-ID
  survivor := bank.session 1 candidate --database-id=DATABASE-ID
  try:
    first.save STATE
    survivor.save STATE
    records.ignore-write = true
    expect-throw "BLE_CCCD_WRITE_NOT_VERIFIED": first.save #[1, 0]
    expect-throw "BLE_CCCD_STORAGE_FAILED": first.load
    expect-equals STATE survivor.load
    records.ignore-write = false
    bank.remove 0
    expect-null first.load
    first.save STATE
    records.fail-after-write = true
    expect-throw "STORAGE_FAILED": first.save #[1, 0]
    expect-throw "BLE_CCCD_STORAGE_FAILED": first.save STATE
    expect-equals STATE survivor.load
    records.fail-after-write = false
    bank.remove 0
    first.save STATE
    records.ignore-delete = true
    expect-throw "BLE_CCCD_DELETE_NOT_VERIFIED": bank.remove 0
    expect-throw "BLE_CCCD_STORAGE_FAILED": first.load
    records.ignore-delete = false
    bank.remove 0
    records.mutate = true
    expect-throw "BLE_CCCD_WRITE_NOT_VERIFIED": first.save STATE
    expect-throw "BLE_CCCD_STORAGE_FAILED": first.load
    records.mutate = false
    bank.remove 0
    first.save #[1, 0]
    expect-equals #[1, 0] first.load
  finally:
    bank.close

flash-reopen:
  path := "toit.test/ble-cccd-protected"
  bank := cccd-storage.Storage (bond-flash.FlashRecords path) (ByteArray 32 --initial=42)
  try:
    bank.remove 0
    (bank.session 0 candidate --database-id=DATABASE-ID).save STATE
  finally:
    bank.close
  bank = cccd-storage.Storage (bond-flash.FlashRecords path) (ByteArray 32 --initial=42)
  try:
    expect-equals STATE (bank.session 0 candidate --database-id=DATABASE-ID).load
    bank.remove 0
    expect-null (bank.session 0 candidate --database-id=DATABASE-ID).load
  finally:
    bank.close
