// Copyright (C) 2026 Toit contributors.

// Generate the PLAT jump table header + source from the set of symbols the
// VM calls into PLAT, plus the matching `-Wl,--wrap=<sym>` ldflags fragment,
// and patch the PLAT_JT_LDFLAGS block in xmake.lua.
//
// This consolidates the two Python helpers (extract_plat_jt_symbols.py +
// gen_plat_jt.py) into one tool. It first extracts the symbol set from the
// VM archives' object relocations, then emits all outputs.
//
// Extraction (robust to the dual-slot split and to existing --wrap flags):
//   1. Read the VM archives' object RELOCATIONS (R_ARM_*_CALL / JUMP24).
//      Relocations carry the *referenced* symbol name from the object — the
//      name the compiler emitted (e.g. `printf`, `__aeabi_dadd`), NOT the
//      link-time-resolved alias. Only the referenced name can be wrapped
//      with `-Wl,--wrap=`, so this is what we must list.
//   2. Drop targets the VM archives define themselves (intra-VM calls).
//   3. Drop an EXCLUDE set of references with no PLAT definition.
//   4. Drop mangled C++ references that resolve to nothing in the final elf.
//   5. Route the manually-wrapped libc time helpers through their `__wrap_*`
//      name (the manual `-Wl,--wrap=time` already rewrites `time`).
//
// The source pairs with `-Wl,--wrap=<sym>` flags in xmake.lua; the wrap
// mechanism rewrites each VM-side call into `__wrap_<sym>`, which the
// generated stub forwards through `g_plat_jt`.

import cli
import host.file
import host.pipe

TOOL-NAME ::= "tools/ec618/gen-plat-jt.toit"

// Manually wrapped (custom RTC-backed) libc helpers (see __wrap.c +
// xmake.lua): the VM's `time` is rewritten to `__wrap_time` by the manual
// `-Wl,--wrap=time`, so the jump table routes `__wrap_time`, not `time`.
MANUAL-WRAP ::= {"clock", "localtime", "gmtime", "time"}

// References with no PLAT definition — present only as dead, GC'd refs. A
// table entry would emit an undefined `__real_*`. Add here if a build fails
// with "undefined reference to ..." from plat_jt.o(.jt_data).
DEFAULT-EXCLUDE ::= {
  // toit::OS::set_writable — only defined for host (os_linux/win/darwin),
  // dead on embedded.
  "_ZN4toit2OS12set_writableEPNS_12ProgramBlockEb",
}

// Relocation types that denote a VM->PLAT call/jump.
CALL-RELOC-TYPES ::= {
  "R_ARM_THM_CALL",
  "R_ARM_CALL",
  "R_ARM_THM_JUMP24",
  "R_ARM_JUMP24",
  "R_ARM_THM_PC22",
  "R_ARM_PLT32",
}

HEADER-TEMPLATE ::= """\
// Copyright (C) 2026 Toit contributors.
// AUTO-GENERATED by $TOOL-NAME — do not edit by hand.
//
// PLAT jump table: one entry per PLAT-side symbol the VM reaches. The
// table is `const` and lives in `.rodata` (flash), so it is reachable
// before C-runtime `.data` initialisation runs. PLAT startup calls
// `memcpy` very early, which is the reason flash-resident matters.

#ifndef PLAT_JT_H_
#define PLAT_JT_H_

#ifdef __cplusplus
extern "C" {
#endif

enum plat_jt_slot {
{{slot_enum}}
    PLAT_JT_COUNT
};

extern void *const g_plat_jt[PLAT_JT_COUNT];

#ifdef __cplusplus
}
#endif

#endif  // PLAT_JT_H_
"""

SOURCE-TEMPLATE ::= """\
// Copyright (C) 2026 Toit contributors.
// AUTO-GENERATED by $TOOL-NAME — do not edit by hand.
//
// Per-symbol wrapper stubs + the jump-table data. Each stub is a
// 16-byte Thumb-2 sequence: load `g_plat_jt[slot]`, tail-call. The
// ABI args (r0-r3 + stack) are already in place by the time the BL
// from the caller lands, so a bare `bx` to the real function preserves
// every argument and return convention.

#include "plat_jt.h"

{{externs}}

// Placed at a fixed flash address (see ec618_0h00_flash.c, .jt_data
// section) so dual-linked VM slots resolve to the same g_plat_jt[]
// regardless of which slot's image they were linked from.
__attribute__((section(".jt_data"), used))
void *const g_plat_jt[PLAT_JT_COUNT] = {
{{table_init}}
};

#define PLAT_STUB(name, slot)                                       \\
    __attribute__((naked, noinline))                                 \\
    void __wrap_##name(void) {                                      \\
        __asm__ volatile (                                           \\
            "movw r12, #:lower16:g_plat_jt + " #slot " * 4 \\n"      \\
            "movt r12, #:upper16:g_plat_jt + " #slot " * 4 \\n"      \\
            "ldr  r12, [r12]                              \\n"       \\
            "bx   r12                                     \\n"       \\
        );                                                           \\
    }

{{stubs}}
"""

LDFLAGS-TEMPLATE ::= """\
-- AUTO-GENERATED by $TOOL-NAME — do not edit by hand.
-- Paste this block between the PLAT_JT_LDFLAGS markers in xmake.lua.
{{ldflags}}
"""

MARKER-BEGIN ::= "-- BEGIN PLAT_JT_LDFLAGS"
MARKER-END ::= "-- END PLAT_JT_LDFLAGS"

/**
Collects the symbols targeted by VM->PLAT call/jump relocations.

Runs `$objdump -r <archive>` for each archive in $archives and returns the
  referenced symbol names (with any `+0x..`/`-0x..` addend stripped).
*/
call-targets objdump/string archives/List -> Set:
  targets := {}
  archives.do: | arc/string |
    out := pipe.backticks [objdump, "-r", arc]
    out.split "\n": | line/string |
      // Relocation lines have the shape `<offset> <RELOC_TYPE> <symbol>`.
      parts := split-whitespace line
      if parts.size < 3: continue.split
      if not CALL-RELOC-TYPES.contains parts[1]: continue.split
      targets.add (strip-addend parts[2])
  return targets

/** Strips a trailing `+0x..` or `-0x..` addend from a relocation symbol. */
strip-addend symbol/string -> string:
  plus := symbol.index-of "+"
  minus := symbol.index-of "-"
  cut := -1
  if plus >= 0: cut = plus
  if minus >= 0 and (cut == -1 or minus < cut): cut = minus
  if cut == -1: return symbol
  return symbol[..cut]

/**
Collects the symbols defined in the given $files.

Runs `$nm --defined-only <file>` and returns the 3rd field (the symbol name)
  of every `<addr> <type> <name>` line.
*/
defined-symbols nm/string files/List -> Set:
  defined := {}
  files.do: | f/string |
    out := pipe.backticks [nm, "--defined-only", f]
    out.split "\n": | line/string |
      parts := split-whitespace line
      if parts.size >= 3: defined.add parts[2]
  return defined

/** Collects all symbols (defined or not) reported by `$nm <file>`. */
all-symbols nm/string file/string -> Set:
  result := {}
  out := pipe.backticks [nm, file]
  out.split "\n": | line/string |
    parts := split-whitespace line
    if parts.is-empty: continue.split
    // Lines are `<addr> <type> <name>` or `<type> <name>` (undefined).
    result.add parts.last
  return result

/** Splits a string on runs of whitespace, dropping empty tokens. */
split-whitespace str/string -> List:
  result := []
  current := []
  str.do: | c/int |
    if c == ' ' or c == '\t':
      if not current.is-empty:
        result.add (string.from-runes current)
        current = []
    else:
      current.add c
  if not current.is-empty:
    result.add (string.from-runes current)
  return result

// TODO(ec618): "generous" jump table. The table currently holds ONLY the
// PLAT symbols the *current* VM happens to call. But the jump table is the
// immutable-PLAT <-> OTA'able-VM ABI: a future VM (OTA'd without reflashing
// PLAT) can only reach PLAT functions that already have a slot here at
// PLAT-build time. To future-proof the ABI we'd want a curated "always
// include" set of likely-useful PLAT API functions (luat_*/BSP_*/GPIO_*/...),
// merged in below in addition to the relocation-derived set, bounded by the
// .jt_data region (4 KB ~= 1024 entries) and the per-slot stub budget
// (16 B/entry/slot). Adding an entry for a function PLAT *already* links is
// cheap (one stub + 4 B, no PLAT growth); adding one that isn't linked pulls
// it in (PLAT growth) — hence the "if they aren't too big" filter. Deferred:
// needs a decision on which API surface and the size budget.

/** Derives the final, sorted symbol list for the jump table. */
extract-symbols --objdump/string --nm/string --elf/string --archives/List --excludes/List -> List:
  targets := call-targets objdump archives
  vm-defined := defined-symbols nm archives
  elf-defined := all-symbols nm elf
  exclude := {}
  exclude.add-all DEFAULT-EXCLUDE
  exclude.add-all excludes

  result := {}
  targets.do: | s/string |
    if vm-defined.contains s: continue.do
    if exclude.contains s: continue.do
    // A mangled C++ reference that resolves to nothing in the final elf is
    // dead VM code; skip it (avoids an undefined __real_*). Plain-C
    // libc/libgcc refs may be GC'd here but the table's KEEP pulls them
    // back, so don't filter those.
    if s.starts-with "_Z" and not (elf-defined.contains s): continue.do
    result.add (MANUAL-WRAP.contains s ? "__wrap_$s" : s)

  sorted := []
  sorted.add-all result
  // Codepoint sort: deterministic and locale-independent. The order only
  // fixes the (internal) jump-table indices, so any stable order is fine.
  sorted.sort --in-place
  return sorted

/** Patches the lines between the PLAT_JT_LDFLAGS markers with $ldflags-body. */
patch-xmake xmake-path/string ldflags-body/string -> none:
  text := (file.read-contents xmake-path).to-string
  begin := text.index-of MARKER-BEGIN
  end := text.index-of MARKER-END
  if begin == -1 or end == -1 or end < begin:
    throw "$xmake-path: missing PLAT_JT_LDFLAGS markers"
  // Replace everything between the marker lines (inclusive of the begin
  // marker's end-of-line up to the end marker).
  before := text[..begin + MARKER-BEGIN.size]
  after := text[end..]
  file.write-contents --path=xmake-path "$before\n$ldflags-body\n$after"

main args:
  cmd := cli.Command "gen-plat-jt"
      --help="""
        Extracts the VM->PLAT call symbol set from the VM archives and
        generates plat_jt.h, plat_jt.c, the ldflags fragment, and patches
        the PLAT_JT_LDFLAGS block in xmake.lua.
        """
      --options=[
        cli.Option "objdump"
            --help="The arm objdump binary."
            --default="arm-none-eabi-objdump",
        cli.Option "nm"
            --help="The arm nm binary."
            --default="arm-none-eabi-nm",
        cli.Option "elf"
            --help="The final linked toit.elf (used to drop dead C++ refs)."
            --required,
        cli.Option "header"
            --help="The output plat_jt.h path."
            --required,
        cli.Option "source"
            --help="The output plat_jt.c path."
            --required,
        cli.Option "ldflags"
            --help="The output ldflags .lua fragment path."
            --required,
        cli.Option "xmake"
            --help="The xmake.lua to patch."
            --required,
        cli.Option "exclude"
            --help="Extra symbol to exclude (repeatable)."
            --multi,
      ]
      --rest=[
        cli.Option "archive"
            --help="VM archives (libtoit_vm.a, libmbed*.a)."
            --required
            --multi,
      ]
      --run=:: run it
  cmd.run args

run invocation/cli.Invocation -> none:
  objdump := invocation["objdump"]
  nm := invocation["nm"]
  elf := invocation["elf"]
  header-path := invocation["header"]
  source-path := invocation["source"]
  ldflags-path := invocation["ldflags"]
  xmake-path := invocation["xmake"]
  excludes := invocation["exclude"]
  archives := invocation["archive"]

  symbols := extract-symbols
      --objdump=objdump
      --nm=nm
      --elf=elf
      --archives=archives
      --excludes=excludes

  if symbols.is-empty:
    pipe.print-to-stderr "no symbols found in input"
    exit 1

  slot-enum-lines := []
  externs-lines := []
  table-init-lines := []
  stubs-lines := []
  ldflags-lines := []
  symbols.size.repeat: | i/int |
    s := symbols[i]
    slot-enum-lines.add "    PLAT_JT_$s = $i,"
    externs-lines.add "extern void *__real_$s;"
    table-init-lines.add "    [PLAT_JT_$s] = &__real_$s,"
    stubs-lines.add "PLAT_STUB($s, $i)"
    ldflags-lines.add "add_ldflags(\" -Wl,--wrap=$s \", {force = true})"

  slot-enum := slot-enum-lines.join "\n"
  externs := externs-lines.join "\n"
  table-init := table-init-lines.join "\n"
  stubs := stubs-lines.join "\n"
  ldflags := ldflags-lines.join "\n"

  header := HEADER-TEMPLATE.replace "{{slot_enum}}" slot-enum
  source := SOURCE-TEMPLATE.replace "{{externs}}" externs
  source = source.replace "{{table_init}}" table-init
  source = source.replace "{{stubs}}" stubs
  ldflags-fragment := LDFLAGS-TEMPLATE.replace "{{ldflags}}" ldflags

  file.write-contents --path=header-path header
  file.write-contents --path=source-path source
  file.write-contents --path=ldflags-path ldflags-fragment
  patch-xmake xmake-path ldflags

  print "Generated $symbols.size stubs."
  print "  header:   $header-path"
  print "  source:   $source-path"
  print "  ldflags:  $ldflags-path"
  print "  xmake.lua: patched"
