// Copyright (C) 2026 Toit contributors.

// Generate the SLOT linker script for the two-stage link (frozen-base
// phase 4, docs/frozen-base-phase4.md).
//
// The slot links separately against the published base:
//   arm-none-eabi-g++ -T <generated>.ld -Wl,--just-symbols=base.elf ...
// so every geometry number in the script COMES FROM base.elf — the script
// is correct for exactly that base, by construction. Slot code captures are
// universal (`*(.text*)` ...): in the slot link every input section belongs
// to the slot, including the slot compiler's own libgcc/libstdc++ members,
// which is what makes the slot self-contained across toolchains.
//
// The .data init image (.vm_dram_data) is placed with its LMA INSIDE the
// slot's flash region, right after the body — so the whole slot link
// occupies only the slot region and splicing it into base.bin
// (tools/ec618/splice-slot.toit) touches no base byte.
//
// `--slot b` generates the slot-B variant (VMA = slot B's flash address,
// mirroring the single-link oracle): the independent second link that
// gen-slot-reloc proves byte-identity against.

import cli
import host.file
import host.pipe

// Geometry symbols read from base.elf. The link base is recovered from
// __vm_link_base (defined by the base link even though its .vm_a is empty).
WANTED ::= {
  "__vm_link_base", "__vm_a_start", "__vm_b_start",
  "__vm_data_start", "end_ap_data", "__toit_rtc_slot",
}

main args:
  cmd := cli.Command "gen-slot-ld"
      --help="""
        Generates the slot linker script from the base link's geometry
        (frozen-base phase 4: the slot links against base.elf).
        """
      --options=[
        cli.Option "nm"
            --help="The arm nm binary."
            --default="arm-none-eabi-nm",
        cli.Option "base-elf"
            --help="The base link (build/ec618-base/base.elf)."
            --required,
        cli.Option "slot"
            --help="Which slot geometry to emit: a (neutral link base) or b."
            --default="a",
        cli.Option "out"
            --help="The output linker-script path."
            --required,
      ]
      --run=:: run it
  cmd.run args

run invocation/cli.Invocation -> none:
  nm := invocation["nm"]
  base-elf := invocation["base-elf"]
  slot := invocation["slot"]
  if slot != "a" and slot != "b":
    pipe.print-to-stderr "--slot must be 'a' or 'b'"
    exit 1

  syms := read-symbols nm base-elf
  WANTED.do: | name/string |
    if not syms.contains name:
      pipe.print-to-stderr "missing geometry symbol $name in $base-elf"
      exit 1

  link-base := syms["__vm_link_base"]
  slot-a := syms["__vm_a_start"]
  slot-b := syms["__vm_b_start"]
  data-vma := syms["__vm_data_start"]
  reserve-end := syms["end_ap_data"]
  rtc-slot := syms["__toit_rtc_slot"]
  slot-size := slot-b - slot-a

  // Slot A links at the neutral base (relocate-on-write localizes it);
  // slot B links at its real flash address — the byte-identity oracle.
  vma := slot == "a" ? link-base : slot-b
  lma := slot == "a" ? slot-a : slot-b
  section := slot == "a" ? ".vm_a" : ".vm_b"

  script := """
/* GENERATED by tools/ec618/gen-slot-ld.toit from $base-elf — do not edit.
 * Slot-$slot link geometry; see docs/frozen-base-phase4.md. */

MEMORY
{
  SLOT_FLASH (rx) : ORIGIN = 0x$(%08x lma), LENGTH = 0x$(%08x slot-size)
}

ENTRY(toit_start)

/* No crt objects in the slot link (-nostartfiles): provide the C++
 * static-destructor registration anchor; atexit never runs here. */
PROVIDE(__dso_handle = 0);

SECTIONS
{
  $section 0x$(%08x vma) :
  {
    __slot_body_start = .;
    KEEP(*(.vm_entry))
    . = ALIGN(4);
    __vm_init_array_start = .;
    KEEP(*(SORT(.init_array.*)))
    KEEP(*(.init_array*))
    __vm_init_array_end = .;
    *(.rodata*)
    *(.text*)
    *(.glue_7)
    *(.glue_7t)
    *(.vfpll_veneer)
    *(.v4_bx)
    . = ALIGN(4);
    __slot_body_end = .;
  } AT>SLOT_FLASH

  /* The link-domain markers are the NEUTRAL link base in EVERY slot link:
   * the VM reads __vm_link_base at runtime to compute its relocation delta,
   * and the value ships un-relocated in the canonical image — so the slot-B
   * oracle link must carry the same constant, not its own section address. */
  __vm_link_base = 0x$(%08x link-base);
  __vm_link_end  = __vm_link_base + (__slot_body_end - __slot_body_start);

  /* Slot flash geometry for the VM's slot math (dispatcher-compatible). */
  __vm_a_start = 0x$(%08x slot-a);
  __vm_a_end   = __vm_a_start + (__vm_link_end - __vm_link_base);
  __vm_b_start = 0x$(%08x slot-b);
  __vm_b_end   = __vm_b_start + (__vm_link_end - __vm_link_base);

  ASSERT(__slot_body_end - __slot_body_start <= 0x$(%08x slot-size),
         "VM slot overflowed the slot reservation")

  /* The VM's writable .data: VMA at the base's reserved RAM region, LMA
   * right after the body inside the slot flash region (the per-slot .data
   * init source; gen-slot-reloc extracts it via these symbols). */
  .vm_dram_data 0x$(%08x data-vma) :
  {
    Load\$\$VM_DRAM_DATA\$\$Base = LOADADDR(.vm_dram_data);
    Image\$\$VM_DRAM_DATA\$\$Base = .;
    __vm_data_start = .;
    *(.data*)
    . = ALIGN(4);
    __vm_data_end = .;
  } AT>SLOT_FLASH

  /* The VM's RTC-noinit region, at the base's exported fixed address —
   * RTC content must survive slot OTAs, so the address is part of the
   * geometry contract (never inside the slot flash image). */
  .toit.rtc.noinit 0x$(%08x rtc-slot) (NOLOAD) :
  {
    *(.toit.rtc.noinit)
  }

  /* The VM's .bss, zeroed by the VM itself at entry (phase 3). */
  .vm_dram_zi (NOLOAD) :
  {
    __vm_zi_start = .;
    *(.bss*)
    *(COMMON)
    . = ALIGN(4);
    __vm_zi_end = .;
  }

  ASSERT(__vm_zi_end <= 0x$(%08x reserve-end),
         "VM .data+.bss exceeded the base's pooled dram reserve")

  /DISCARD/ :
  {
    *(.ARM.exidx*)
    *(.ARM.extab*)
    *(.ARM.attributes)
    *(.comment)
  }
}
"""
  file.write-contents --path=invocation["out"] script
  print "slot-$slot ld: vma=0x$(%x vma) lma=0x$(%x lma) data-vma=0x$(%x data-vma) -> $invocation["out"]"

/** Reads the $WANTED symbol addresses from `$nm $elf`. */
read-symbols nm/string elf/string -> Map:
  result := {:}
  out := pipe.backticks [nm, elf]
  out.split "\n": | line/string |
    parts := line.split " "
    if parts.size >= 3 and WANTED.contains parts.last:
      result[parts.last] = int.parse parts[0] --radix=16
  return result
