#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := toit
BUILD_DIR_BASE := $(abspath ../../build/esp32)
include $(IDF_PATH)/make/project.mk
