#!/usr/bin/env python3
# Copyright (C) 2026 Toit contributors.
# Generate the PLAT jump table header + source from a list of symbols
# the VM calls into PLAT. The source pairs with `-Wl,--wrap=<sym>` flags
# in xmake.lua; the wrap mechanism rewrites each VM-side call into
# `__wrap_<sym>`, which the generated stub forwards through `g_plat_jt`.
#
# Usage: gen_plat_jt.py <symbols-file> <out-header> <out-source> <out-ldflags>
#   symbols-file: one symbol per line (leading whitespace + count tolerated)
#   out-header:   plat_jt.h
#   out-source:   plat_jt.c
#   out-ldflags:  text fragment to paste into xmake.lua

import sys
from pathlib import Path

HEADER_TEMPLATE = """\
// Copyright (C) 2026 Toit contributors.
// AUTO-GENERATED by tools/gen_plat_jt.py — do not edit by hand.
//
// PLAT jump table: one entry per PLAT-side symbol the VM reaches. The
// table is `const` and lives in `.rodata` (flash), so it is reachable
// before C-runtime `.data` initialisation runs. PLAT startup calls
// `memcpy` very early, which is the reason flash-resident matters.

#ifndef PLAT_JT_H_
#define PLAT_JT_H_

#ifdef __cplusplus
extern "C" {{
#endif

enum plat_jt_slot {{
{slot_enum}
    PLAT_JT_COUNT
}};

extern void *const g_plat_jt[PLAT_JT_COUNT];

#ifdef __cplusplus
}}
#endif

#endif  // PLAT_JT_H_
"""

SOURCE_TEMPLATE = """\
// Copyright (C) 2026 Toit contributors.
// AUTO-GENERATED by tools/gen_plat_jt.py — do not edit by hand.
//
// Per-symbol wrapper stubs + the jump-table data. Each stub is a
// 16-byte Thumb-2 sequence: load `g_plat_jt[slot]`, tail-call. The
// ABI args (r0-r3 + stack) are already in place by the time the BL
// from the caller lands, so a bare `bx` to the real function preserves
// every argument and return convention.

#include "plat_jt.h"

{externs}

// Placed at a fixed flash address (see ec618_0h00_flash.c, .jt_data
// section) so dual-linked VM slots resolve to the same g_plat_jt[]
// regardless of which slot's image they were linked from.
__attribute__((section(".jt_data"), used))
void *const g_plat_jt[PLAT_JT_COUNT] = {{
{table_init}
}};

#define PLAT_STUB(name, slot)                                       \\
    __attribute__((naked, noinline))                                 \\
    void __wrap_##name(void) {{                                      \\
        __asm__ volatile (                                           \\
            "movw r12, #:lower16:g_plat_jt + " #slot " * 4 \\n"      \\
            "movt r12, #:upper16:g_plat_jt + " #slot " * 4 \\n"      \\
            "ldr  r12, [r12]                              \\n"       \\
            "bx   r12                                     \\n"       \\
        );                                                           \\
    }}

{stubs}
"""

LDFLAGS_TEMPLATE = """\
-- AUTO-GENERATED by tools/gen_plat_jt.py — do not edit by hand.
-- Paste this block between the PLAT_JT_LDFLAGS markers in xmake.lua.
{ldflags}
"""


def load_symbols(path):
    """Read symbol names; ignores leading counts/whitespace, blanks, comments."""
    syms = []
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        # Lines may be either bare names or "<count>  <name>".
        parts = line.split()
        name = parts[-1]
        syms.append(name)
    # Preserve order while removing duplicates.
    seen = set()
    uniq = []
    for s in syms:
        if s not in seen:
            seen.add(s)
            uniq.append(s)
    return uniq


MARKER_BEGIN = "-- BEGIN PLAT_JT_LDFLAGS"
MARKER_END = "-- END PLAT_JT_LDFLAGS"


def patch_xmake(xmake_path: Path, ldflags_body: str) -> None:
    """Replace the lines between PLAT_JT_LDFLAGS markers with `ldflags_body`."""
    text = xmake_path.read_text()
    begin = text.find(MARKER_BEGIN)
    end = text.find(MARKER_END)
    if begin == -1 or end == -1 or end < begin:
        raise RuntimeError(
            f"{xmake_path}: missing PLAT_JT_LDFLAGS markers")
    # Replace everything between the marker lines (inclusive of marker end-of-line).
    before = text[:begin + len(MARKER_BEGIN)]
    after = text[end:]
    xmake_path.write_text(f"{before}\n{ldflags_body}\n{after}")


def main(argv):
    if len(argv) != 6:
        sys.stderr.write(
            f"usage: {argv[0]} <symbols-file> <out-header> <out-source> <out-ldflags> <xmake.lua>\n"
        )
        return 1

    symbols = load_symbols(Path(argv[1]))
    if not symbols:
        sys.stderr.write("no symbols found in input\n")
        return 1

    slot_enum = "\n".join(f"    PLAT_JT_{s} = {i}," for i, s in enumerate(symbols))
    externs = "\n".join(f"extern void *__real_{s};" for s in symbols)
    table_init = "\n".join(
        f"    [PLAT_JT_{s}] = &__real_{s}," for s in symbols
    )
    stubs = "\n".join(f"PLAT_STUB({s}, {i})" for i, s in enumerate(symbols))
    ldflags = "\n".join(
        f'add_ldflags(" -Wl,--wrap={s} ", {{force = true}})' for s in symbols
    )

    Path(argv[2]).write_text(HEADER_TEMPLATE.format(slot_enum=slot_enum))
    Path(argv[3]).write_text(SOURCE_TEMPLATE.format(
        externs=externs, table_init=table_init, stubs=stubs))
    Path(argv[4]).write_text(LDFLAGS_TEMPLATE.format(ldflags=ldflags))
    patch_xmake(Path(argv[5]), ldflags)

    print(f"Generated {len(symbols)} stubs.")
    print(f"  header:   {argv[2]}")
    print(f"  source:   {argv[3]}")
    print(f"  ldflags:  {argv[4]}")
    print(f"  xmake.lua: patched")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
