#!/usr/bin/env bash

# Copyright (C) 2021 Toitware ApS.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; version
# 2.1 only.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# The license can be found in the file `LICENSE` in the top level
# directory of this repository.

set -e

# Make sure git is installed and we are in a git tree.
command -v git >/dev/null                       || { echo "UNKNOWN"; exit 0; }
git rev-parse --is-inside-work-tree &>/dev/null || { echo "UNKNOWN"; exit 0; }


CURRENT_COMMIT=$(git rev-parse HEAD)
CURRENT_COMMIT_SHORT=$(git rev-parse --short HEAD)
LATEST_VERSION_TAG=$(git describe --tags --match "v[0-9]*" --abbrev=0 `git rev-list --tags --max-count=1` 2>/dev/null || echo "")

if [ "$LATEST_VERSION_TAG" != "" ]; then
  VERSION_TAG_COMMIT=$(git rev-parse $LATEST_VERSION_TAG^{})
  CURRENT_COMMIT_NO=$(git rev-list --count HEAD ^$VERSION_TAG_COMMIT)
else
  LATEST_VERSION_TAG="v0.0.0"
  VERSION_TAG_COMMIT="UNKNOWN"
  CURRENT_COMMIT_NO=$(git rev-list --count HEAD)
fi

if [ "$VERSION_TAG_COMMIT" == "$CURRENT_COMMIT" ]; then
    # Always use the tag if the current commit is the tag.
    echo "$LATEST_VERSION_TAG"
else
    echo "$CURRENT_COMMIT_SHORT"
fi
