dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.4.1
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.11.0
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^2.5.0
  desktop:
    url: github.com/toitlang/pkg-desktop
    version: ^1.1.0
  fs:
    url: github.com/toitlang/pkg-fs
    version: ^2.3.1
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.16.2
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.9.0
  partition-table:
    url: github.com/toitware/toit-partition-table-esp32
    version: ^1.4.0
  semver:
    url: github.com/toitware/toit-semver
    version: ^1.1.0
  tar:
    url: github.com/toitlang/pkg-tar
    version: ^1.2.0
