dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.0.1
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.7.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.14.1
  partition-table:
    url: github.com/toitware/toit-partition-table-esp32
    version: ^1.1.1
  semver:
    url: github.com/toitware/toit-semver
    version: ^1.1.0
