dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.0.0
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.2.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.8.1
