dependencies:
  ar:
    url: github.com/toitlang/pkg-ar
    version: ^1.4.1
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.11.0
  cli:
    path: ../../../pkg-cli
  fs:
    url: github.com/toitlang/pkg-fs
    version: ^2.3.1
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.16.2
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.9.0
  lockfile:
    path: ../../../toit-lockfile
