// GENERATED FILE — DO NOT EDIT.
// Source of truth: toolchains/ec618/partitions.yaml. Regenerate with:
//   build/host/sdk/bin/toit tools/ec618/gen-partitions.toit \
//       --out toolchains/ec618/project/inc/toit_partitions.h \
//       toolchains/ec618/partitions.yaml
//
// Offsets are RAW flash addresses; _XIP adds the memory-mapped view.
#pragma once

#define TOIT_PART_XIP_OFFSET 0x00800000u

// headers (locked)
#define TOIT_PART_HEADERS_OFFSET 0x00000000u
#define TOIT_PART_HEADERS_SIZE   0x00004000u
#define TOIT_PART_HEADERS_XIP    (TOIT_PART_HEADERS_OFFSET + TOIT_PART_XIP_OFFSET)

// bootloader (locked)
#define TOIT_PART_BOOTLOADER_OFFSET 0x00004000u
#define TOIT_PART_BOOTLOADER_SIZE   0x00020000u
#define TOIT_PART_BOOTLOADER_XIP    (TOIT_PART_BOOTLOADER_OFFSET + TOIT_PART_XIP_OFFSET)

// base (base)
#define TOIT_PART_BASE_OFFSET 0x00024000u
#define TOIT_PART_BASE_SIZE   0x0016c000u
#define TOIT_PART_BASE_XIP    (TOIT_PART_BASE_OFFSET + TOIT_PART_XIP_OFFSET)

// base-id (base-id)
#define TOIT_PART_BASE_ID_OFFSET 0x00190000u
#define TOIT_PART_BASE_ID_SIZE   0x00001000u
#define TOIT_PART_BASE_ID_XIP    (TOIT_PART_BASE_ID_OFFSET + TOIT_PART_XIP_OFFSET)

// ota-a (slot)
#define TOIT_PART_OTA_A_OFFSET 0x00191000u
#define TOIT_PART_OTA_A_SIZE   0x000c0000u
#define TOIT_PART_OTA_A_XIP    (TOIT_PART_OTA_A_OFFSET + TOIT_PART_XIP_OFFSET)

// ota-b (slot)
#define TOIT_PART_OTA_B_OFFSET 0x00251000u
#define TOIT_PART_OTA_B_SIZE   0x000c0000u
#define TOIT_PART_OTA_B_XIP    (TOIT_PART_OTA_B_OFFSET + TOIT_PART_XIP_OFFSET)

// marker (marker)
#define TOIT_PART_MARKER_OFFSET 0x00311000u
#define TOIT_PART_MARKER_SIZE   0x00002000u
#define TOIT_PART_MARKER_XIP    (TOIT_PART_MARKER_OFFSET + TOIT_PART_XIP_OFFSET)

// free (free)
#define TOIT_PART_FREE_OFFSET 0x00313000u
#define TOIT_PART_FREE_SIZE   0x00071000u
#define TOIT_PART_FREE_XIP    (TOIT_PART_FREE_OFFSET + TOIT_PART_XIP_OFFSET)

// littlefs (locked)
#define TOIT_PART_LITTLEFS_OFFSET 0x00384000u
#define TOIT_PART_LITTLEFS_SIZE   0x00048000u
#define TOIT_PART_LITTLEFS_XIP    (TOIT_PART_LITTLEFS_OFFSET + TOIT_PART_XIP_OFFSET)

// registry (data)
#define TOIT_PART_REGISTRY_OFFSET 0x003cc000u
#define TOIT_PART_REGISTRY_SIZE   0x00010000u
#define TOIT_PART_REGISTRY_XIP    (TOIT_PART_REGISTRY_OFFSET + TOIT_PART_XIP_OFFSET)

// nvram-factory (locked)
#define TOIT_PART_NVRAM_FACTORY_OFFSET 0x003dc000u
#define TOIT_PART_NVRAM_FACTORY_SIZE   0x00004000u
#define TOIT_PART_NVRAM_FACTORY_XIP    (TOIT_PART_NVRAM_FACTORY_OFFSET + TOIT_PART_XIP_OFFSET)

// nvram (locked)
#define TOIT_PART_NVRAM_OFFSET 0x003e0000u
#define TOIT_PART_NVRAM_SIZE   0x00004000u
#define TOIT_PART_NVRAM_XIP    (TOIT_PART_NVRAM_OFFSET + TOIT_PART_XIP_OFFSET)

// hib-backup (locked)
#define TOIT_PART_HIB_BACKUP_OFFSET 0x003e4000u
#define TOIT_PART_HIB_BACKUP_SIZE   0x00018000u
#define TOIT_PART_HIB_BACKUP_XIP    (TOIT_PART_HIB_BACKUP_OFFSET + TOIT_PART_XIP_OFFSET)

// plat-config (locked)
#define TOIT_PART_PLAT_CONFIG_OFFSET 0x003fc000u
#define TOIT_PART_PLAT_CONFIG_SIZE   0x00001000u
#define TOIT_PART_PLAT_CONFIG_XIP    (TOIT_PART_PLAT_CONFIG_OFFSET + TOIT_PART_XIP_OFFSET)

// reset-info (locked)
#define TOIT_PART_RESET_INFO_OFFSET 0x003fd000u
#define TOIT_PART_RESET_INFO_SIZE   0x00001000u
#define TOIT_PART_RESET_INFO_XIP    (TOIT_PART_RESET_INFO_OFFSET + TOIT_PART_XIP_OFFSET)

// excep-info (locked)
#define TOIT_PART_EXCEP_INFO_OFFSET 0x003fe000u
#define TOIT_PART_EXCEP_INFO_SIZE   0x00001000u
#define TOIT_PART_EXCEP_INFO_XIP    (TOIT_PART_EXCEP_INFO_OFFSET + TOIT_PART_XIP_OFFSET)

// reserved-tail (locked)
#define TOIT_PART_RESERVED_TAIL_OFFSET 0x003ff000u
#define TOIT_PART_RESERVED_TAIL_SIZE   0x00001000u
#define TOIT_PART_RESERVED_TAIL_XIP    (TOIT_PART_RESERVED_TAIL_OFFSET + TOIT_PART_XIP_OFFSET)

// Both VM slots share one size.
#define TOIT_PART_SLOT_SIZE 0x000c0000u
