name: Build Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        run: |
          choco install ninja cmake
          ninja --version
          cmake --version
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: make
        env:
          IDF_PATH: ${{github.workspace}}/third_party/esp-idf
        run: make tools
      - uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: |
            build/host/bin/toit*
            build/host/bin/lib/
