name: Build Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install dependencies
        run: |
          choco install ninja cmake
          ninja --version
          cmake --version
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: make
        env:
          IDF_PATH: ${{github.workspace}}/third_party/esp-idf
        run: make tools
      - name: Pack artifacts
        run: |
          cp -R ./build/host/sdk ./build/host/toit
          tar -czf build/toit-windows.tar.gz -C ./build/host -h --exclude toit/bin/mbedtls toit
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/toit-windows.tar.gz
      - name: Upload release artifacts
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/toit-windows.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
