# Zero-Clause BSD License

# Copyright (C) 2026 Toit contributors.

# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

name: CI EC618

on:
  push:
    branches:
      - "floitsch/ec618"
      - "floitsch/formatter.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-linux

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build SDK
        run: make

      - name: Build EC618 base
        run: make ec618-base

      - name: Build EC618 firmware (slot vs base + guards + envelope)
        run: make ec618
