name: CI

on:
  push:
    branches-ignore:
      - "wip/**"
      - "wip-**"
      - "*/wip-**"
      - "*/wip/**"
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      # Use 'inputs.<name>' when pasting into a bash `if`, like so:
      #    if [[ "${{ inputs.strip }}" == 'true' ]]; then ...
      #
      # When using to guard a step, use 'github.event.inputs.<name>', like so:
      #    if: ${{ github.event.inputs.<name> == 'true' }}
      # or
      #    if: ${{ github.event.inputs.<name> != 'false' }}
      # In the first case, the step will not run if there isn't any workflow dispatch.
      # In the second case, the step will run if there isn't any workflow dispatch.
      # As such, the recommendation is to use the `== true` if the default is
      # false, and the `!= false` if the default is true.
      strip:
        description: "Strip executables"
        required: false
        type: boolean
        default: false
      sign-macos:
        description: "Sign macOS executables"
        required: false
        type: boolean
        default: false
      build-arm-macos:
        description: "Build ARM macOS executables"
        required: false
        type: boolean
        default: false
      run-tests:
        description: "Run tests"
        required: false
        type: boolean
        default: true

env:
  ESPTOOL_VERSION: v4.6

jobs:
  build:
    strategy:
      # The matrix will run all possible combinations in parallel.
      matrix:
        container: [windows-latest]
        shard: [1]

    runs-on: ${{ matrix.container }}

    steps:
      - name: Show inputs
        if: github.event_name == 'workflow_dispatch'
        run: echo "${{ toJSON(github.event.inputs) }}"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - shell: bash
        run: echo $PATH

      # Run ssh.
      - uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: "${{ secrets.NGROK_FLORIAN }}"
          SSH_PASS: "aoeuAOEU0"
